### ISSUE TITLE
Git is a complex tool

### ISSUE THREAD

**Issue by aabedraba** [Team4Rookies/website#1]
[Git is a complex tool](https://hadihariri.com/2020/10/14/a-few-words-on-git/). And Github is built on top of it. 

When I was at Jaen's uni I started a similar idea. I created a Google Drive folder where everyone contributed with their class notes and content they'd find. People would be able to contribute, but I had to supervise the contributions. Mainly to avoid duplication, give structure to the content and keep hygiene in the platform. 

With a lot of work of advocacy I got at the end of the first year over a hundred contributions from 30 different students and until now the folder is ongoing and I'm being consulted upon it every now and then. There's a team now of 4 supervisors to the folder. 

Someone from the following years tried to [replicate the same idea but using GitHub](https://github.com/Stuja/stuja). The structure was perfect, the idea was simple and clear. But most of **computer science students** didn't know how to use git and so the project went nowhere.

When it comes to educating the contributors, in this case high school students, about git, I feel that mostly it could come as unnecessarily esoteric. In case my suppositions are true, this will act as a strong barrier of entry to contribute to the content.

I've been thinking that building a website where contributions can be made in situ and with a couple of clicks would make the content grow rapidly, by reducing the friction to the first contribution and not making the kids or any other senior but non-technical professionals have to learn about git and GitHub. [This could be easily implemented](https://github.com/sparksuite/simplemde-markdown-editor).

I don't think keeping git and GitHub as the contributing platform is a bad idea and in case we follow that route I would happily focus on it. For CS professionals, it's a game-changer to have a mature GitHub with open source contributions. 

So....... what do you think? Do you think that git is an adequate tool for this? What things do you think that git would add to the vision?

Edit: Another alternative would be having a hybrid approach.

**Comment by almo** [comment]
Keep in mind that this website is the main site of the Team4Rookies project.  Only webadmin and other senior technical contributors will deal with it. Thus, Git should not a problem....

We don't expect to have contribution from the participants in the collaborative learning groups. For them learning Git is part of the overall learning process and thus it is important.  Each of them will produce educational resources but that is different story: we don't expect this content being focus in the look and feel, but also in the content itself.
